version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-n8n_db}
      POSTGRES_USER: ${POSTGRES_USER:-n8n_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-n8n_user}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # n8n workflow automation
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n_db}
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8n_user}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      N8N_HOST: ${N8N_HOST:-0.0.0.0}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      NODE_ENV: production
      GENERIC_TIMEZONE: ${TZ:-UTC}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

  # Nocobase application
  nocobase:
    image: nocobase/nocobase:latest
    restart: unless-stopped
    ports:
      - "13000:13000"
    environment:
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${NOCABASE_DB:-nocobase_db}
      DB_USER: ${POSTGRES_USER:-n8n_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      APP_PORT: 13000
      APP_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - nocobase_storage:/app/storage
    networks:
      - app-network

  # Database Manager (Adminer)
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DATABASE: ${POSTGRES_DB:-n8n_db}
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local
  nocobase_storage:
    driver: local

networks:
  app-network:
    driver: bridge