FROM docker:latest

# Docker Compose kurulumu
RUN apk add --no-cache py3-pip python3-dev libffi-dev openssl-dev gcc libc-dev make && \
    pip3 install docker-compose

# Uygulama dizini oluştur
WORKDIR /app

# Docker compose dosyasını kopyala
COPY docker-compose.yml ./

# Başlangıç scripti
CMD ["docker-compose", "up", "-d"]
